# Generated by Django 4.0.1 on 2022-01-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseñas',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reseñas',
            old_name='Mensaje',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='reseñas',
            name='Email',
        ),
    ]
