# Generated by Django 4.0.1 on 2022-01-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_email_registro_emailregis_and_more'),
        ('AppCoder', '0006_rename_fecha_reseñas_fecha_and_more'),
    ]

    operations = [
    ]
