# Generated by Django 3.2.7 on 2022-02-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_post_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date',
        ),
    ]
