# Generated by Django 4.0.1 on 2022-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_perfiles_delete_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
