# Generated by Django 4.0.1 on 2022-02-21 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0015_perfiles_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagenDePerfil',
            new_name='Image',
        ),
    ]
